### ISSUE TITLE
Model load error

### ISSUE THREAD

**Issue by niteshroyal** [asahi417/relbert#6]
I am getting the following error:

Python 3.7.13 (default, Mar 29 2022, 02:18:16) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from relbert import RelBERT
2023-02-07 20:38:01.014592: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
>>> model = RelBERT()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/c.scmnk4/.conda/envs/tensor/lib/python3.7/site-packages/relbert/lm.py", line 132, in __init__
    self.mode = self.model_config.relbert_config['mode']
KeyError: 'mode'
>>> 

Could you please check it?

**Comment by asahi417** [comment]
Could you update the RelBERT version? It seems that you are on the old version.

`pip install -U relbert`

**Comment by niteshroyal** [comment]
Thanks. 

Indeed I was using an old version.
